### ISSUE TITLE
Errors running builder 'CF Component Builder'

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#75]
I updated cfeclipse to 1.5.2.201611280044, save a cfm file and get an error
```
Errors occurred during the build.
Errors running builder 'CF Component Builder' on project '[...]'.
cfml.dictionary.Tag.isEndtagrequired()Z
```
When I look into `Error Log` tab I see `Exception Stack Trace`
```
java.lang.NoSuchMethodError: cfml.dictionary.Tag.isEndtagrequired()Z
	at cfml.parsing.cfmentat.tag.CFMLTags.register(CFMLTags.java:51)
	at cfml.parsing.CFMLSource.<init>(CFMLSource.java:26)
	at com.cflint.CFLint.process(CFLint.java:272)
	at com.cflint.CFLint.scan(CFLint.java:219)
	at org.cfeclipse.cfml.builders.CFEBuilder.getResourceBuildMarkers(CFEBuilder.java:123)
	at org.cfeclipse.cfml.builders.CFEBuilder.access$0(CFEBuilder.java:89)
	at org.cfeclipse.cfml.builders.CFEBuilder$1.visit(CFEBuilder.java:73)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at org.cfeclipse.cfml.builders.CFEBuilder.incrementalBuild(CFEBuilder.java:71)
	at org.cfeclipse.cfml.builders.CFEBuilder.build(CFEBuilder.java:62)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

I don't fully understand.
Is there an error in your error reporter?
Am I able to see where the (optional; the code works in CF 11) end tag is missing?

Best,
Bernhard

**Comment by denuno** [comment]
I marked the cfparser bundle as a singleton, which seems to have fixed this.  Can you give it a try and see?  It should show up when you check for updates, but if not you can do Help > Install New Software and enter this site: http://cfeclipse.org/cfparser/update-dev/

**Comment by bardware** [comment]
No success.
I started with a fresh eclipse install. I extracted the platform runtime binary and set up 4 update sites:
http://cfeclipse.org/update-dev/
http://cfeclipse.org/cfparser/update-dev/
http://cfeclipse.org/update/
http://cfeclipse.org/cflint/update/

I installed cfeclipse from update-dev. 
I open a cfm file, simply write `<cfdump>` and save. The `NoSuchMethodError` error comes up.

**Comment by denuno** [comment]
Give it a go again, I think I sussed what was going on out, and you shouldn't have to add any more than the cfeclipse update-dev site now-- the rest should get added automatically.

Note that the cflint lib is the latest, and now has its own project preference, so you may have to re-enable it there (context+click on project > properties > CFLint).

**Comment by bardware** [comment]
Exception no longer occurs
