### ISSUE TITLE
cfml.parsing.cfscript.CFFunctionExpression.getArgs()

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#83]
Hi,

I finally understood your [comment](https://github.com/cfeclipse/cfeclipse/issues/81#issuecomment-296389205).
I wanted to update subversive plugin and did a search for updates over all update sites. I realized you updated [CFLint Repo](http://cfeclipse.org/cflint/update-dev/) and [CFParser](http://cfeclipse.org/cfparser/update-dev/)
I uninstalled CFEclipse and reinstalled from update-dev
Now I keep getting get an error:
Either as popup
`Building workspace has encountered a problem`
```
Errors running builder 'CF Component Builder' on project 'XXX'.
cfml.parsing.cfscript.CFFunctionExpression.getArgs()Ljava/util/Vector;
```

Or a large stack trace:
```
java.lang.NoSuchMethodError: cfml.parsing.cfscript.CFFunctionExpression.getArgs()Ljava/util/Vector;
	at com.cflint.tools.CFNestedExpressionProvider.getChildExpressions(CFNestedExpressionProvider.java:46)
	at com.cflint.CFLint.process(CFLint.java:677)
	at com.cflint.CFLint.process(CFLint.java:293)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:322)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:350)
	at com.cflint.CFLint.processStack(CFLint.java:228)
	at com.cflint.CFLint.process(CFLint.java:204)
	at com.cflint.CFLint.scan(CFLint.java:164)
	at org.cfeclipse.cflint.CFLintPlugin.addMarkers(CFLintPlugin.java:109)
	at org.cfeclipse.cflint.CFLintBuilder.getResourceBuildMarkers(CFLintBuilder.java:83)
	at org.cfeclipse.cflint.CFLintBuilder.access$0(CFLintBuilder.java:82)
	at org.cfeclipse.cflint.CFLintBuilder$CFMLBuildVisitor.visit(CFLintBuilder.java:88)
	at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at org.cfeclipse.cflint.CFLintBuilder.fullBuild(CFLintBuilder.java:77)
	at org.cfeclipse.cflint.CFLintBuilder.build(CFLintBuilder.java:49)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:403)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:551)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
	at org.eclipse.core.internal.resources.Project.build(Project.java:112)
	at org.cfeclipse.cflint.config.CFLintConfigUI.setProjectRules(CFLintConfigUI.java:133)
	at org.cfeclipse.cflint.store.ProjectPropertyPage.performOk(ProjectPropertyPage.java:120)
	at org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:905)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:889)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:409)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:230)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:157)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by bardware** [comment]
I see you updated CFLint plugin to 1.0.10.201705040256 but I don't see a change.

**Comment by bardware** [comment]
I see you updated CFLint plugin to 1.0.10.201705150028.
The Stack trace now logs line 680 between 677 and 293.

```
java.lang.NoSuchMethodError: cfml.parsing.cfscript.CFFunctionExpression.getArgs()Ljava/util/Vector;
	at com.cflint.tools.CFNestedExpressionProvider.getChildExpressions(CFNestedExpressionProvider.java:46)
	at com.cflint.CFLint.process(CFLint.java:677)
	at com.cflint.CFLint.process(CFLint.java:680)
	at com.cflint.CFLint.process(CFLint.java:293)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:374)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:322)
	at com.cflint.CFLint.processStack(CFLint.java:246)
	at com.cflint.CFLint.process(CFLint.java:350)
	at com.cflint.CFLint.processStack(CFLint.java:228)
	at com.cflint.CFLint.process(CFLint.java:204)
	at com.cflint.CFLint.scan(CFLint.java:164)
	at org.cfeclipse.cflint.CFLintPlugin.addMarkers(CFLintPlugin.java:109)
	at org.cfeclipse.cflint.CFLintBuilder.getResourceBuildMarkers(CFLintBuilder.java:83)
	at org.cfeclipse.cflint.CFLintBuilder.access$0(CFLintBuilder.java:82)
	at org.cfeclipse.cflint.CFLintBuilder$1.visit(CFLintBuilder.java:66)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at org.cfeclipse.cflint.CFLintBuilder.incrementalBuild(CFLintBuilder.java:64)
	at org.cfeclipse.cflint.CFLintBuilder.build(CFLintBuilder.java:55)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by bardware** [comment]
@denuno there's now a dependency missing

```
java.lang.NoClassDefFoundError: org/apache/commons/io/input/BOMInputStream
	at com.cflint.CFLint.scan(CFLint.java:189)
	at org.cfeclipse.cflint.CFLintPlugin.addMarkers(CFLintPlugin.java:111)
	at org.cfeclipse.cflint.CFLintBuilder.getResourceBuildMarkers(CFLintBuilder.java:83)
	at org.cfeclipse.cflint.CFLintBuilder.access$0(CFLintBuilder.java:82)
	at org.cfeclipse.cflint.CFLintBuilder$CFMLBuildVisitor.visit(CFLintBuilder.java:88)
	at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
	at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	at org.cfeclipse.cflint.CFLintBuilder.fullBuild(CFLintBuilder.java:77)
	at org.cfeclipse.cflint.CFLintBuilder.build(CFLintBuilder.java:49)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.input.BOMInputStream cannot be found by org.cfeclipse.cflint_1.1.0.201706110228
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```

**Comment by bardware** [comment]
> @denuno there's now a dependency missing

I eventually looked into the `.jar` using Java Decompiler.
Your [.classpath file](https://github.com/cfeclipse/cflint-eclipse/blob/develop/org.cfeclipse.cflint/.classpath) lists a dependency `lib/commons-io.jar`. 
This file has not made it into the [JAR ](http://cfeclipse.org/cflint/update-dev) delivered from.
![grafik](https://user-images.githubusercontent.com/802702/27280304-c327d844-54e7-11e7-9904-78ddedaa4de8.png)

I have not found out where and how BOMInputStream is being used :(

**Comment by bardware** [comment]
CFlint uses BOMInputStream on [this](https://github.com/cflint/CFLint/blob/master/src/main/java/com/cflint/tools/FileUtil.java) occasion

**Comment by bardware** [comment]
When I build the complete CFLint package using: `mvn clean package` commons.io is included:

![image](https://user-images.githubusercontent.com/802702/27355017-c7273a16-5609-11e7-97fe-b597fd4ce041.png)

**Comment by bardware** [comment]
This seems fixed with version org.cfeclipse.cflint_1.1.0.201706222216.jar
