### ISSUE TITLE
org.eclipse.core.runtime.AssertionFailedException: unknown saveable

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#84]
Since updateing to 1.5.3 from update-dev including `cfparser_2.4.5.201704220244` I sometimes get error
```
org.eclipse.core.runtime.AssertionFailedException: unknown saveable: org.eclipse.ui.texteditor.AbstractTextEditor$TextEditorSavable@34d1843e from part: org.cfeclipse.cfml.editors.CFMLEditor@2a1ad676
	at org.eclipse.ui.internal.SaveablesList.logWarning(SaveablesList.java:190)
	at org.eclipse.ui.internal.SaveablesList.removeModel(SaveablesList.java:169)
	at org.eclipse.ui.internal.SaveablesList.removeModels(SaveablesList.java:274)
	at org.eclipse.ui.internal.SaveablesList.handleLifecycleEvent(SaveablesList.java:244)
	at org.eclipse.ui.texteditor.AbstractTextEditor.doSetInput(AbstractTextEditor.java:4158)
	at org.eclipse.ui.texteditor.StatusTextEditor.doSetInput(StatusTextEditor.java:229)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.doSetInput(AbstractDecoratedTextEditor.java:1466)
	at org.eclipse.ui.editors.text.TextEditor.doSetInput(TextEditor.java:150)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setInputWithNotify(AbstractTextEditor.java:4239)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setInput(AbstractTextEditor.java:4259)
	at org.eclipse.search.internal.ui.text.EditorOpener.showWithReuse(EditorOpener.java:106)
	at org.eclipse.search.internal.ui.text.EditorOpener.openAndSelect(EditorOpener.java:58)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.openAndSelect(AbstractTextSearchViewPage.java:449)
	at org.eclipse.search.internal.ui.text.FileSearchPage.showMatch(FileSearchPage.java:184)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage$6.run(AbstractTextSearchViewPage.java:940)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.showMatch(AbstractTextSearchViewPage.java:943)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.showCurrentMatch(AbstractTextSearchViewPage.java:1008)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.gotoPreviousMatch(AbstractTextSearchViewPage.java:992)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.gotoPreviousMatch(AbstractTextSearchViewPage.java:982)
	at org.eclipse.search2.internal.ui.basic.views.ShowPreviousResultAction.run(ShowPreviousResultAction.java:33)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
```

**Comment by denuno** [comment]
Hmm, that looks kind of like it's trying to maybe list a file that was in a search result that doesn't exist any more?  Can you reproduce it at will, or is it a rando? :smiley:
