### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by bardware** [cfeclipse/cfeclipse#89]
Eclipse once in a while displays my files broken, while they are being saved correctly.
Just now I see a stacktrace including cfeclipse

```
java.lang.IllegalStateException
	at org.eclipse.jface.text.projection.ProjectionTextStore.internalError(ProjectionTextStore.java:81)
	at org.eclipse.jface.text.projection.ProjectionTextStore.get(ProjectionTextStore.java:138)
	at org.eclipse.jface.text.AbstractDocument.get(AbstractDocument.java:966)
	at org.eclipse.jface.text.DefaultDocumentAdapter.getTextRange(DefaultDocumentAdapter.java:223)
	at org.eclipse.swt.custom.StyledText.getText(StyledText.java:5155)
	at org.cfeclipse.cfml.editors.decoration.MatchingCharacterPainter.draw(MatchingCharacterPainter.java:217)
	at org.cfeclipse.cfml.editors.decoration.MatchingCharacterPainter.handleDrawRequest(MatchingCharacterPainter.java:173)
	at org.cfeclipse.cfml.editors.decoration.MatchingCharacterPainter.paintControl(MatchingCharacterPainter.java:125)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:231)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1570)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4900)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by aousterhout** [comment]
I am having the same problem on a regular basis.  Is CFEclipse compatible with Version: 2019-03 (4.11.0)
Build id: 20190314-1200?

Thanks,
Andy
